## 数据源配置
#spring:
#    datasource:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driverClassName: com.mysql.cj.jdbc.Driver
#        druid:
#            # 主库数据源
#            master:
#                url: jdbc:mysql://localhost:3306/ry?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#                username: root
#                password: password
#            # 从库数据源
#            slave:
#                # 从数据源开关/默认关闭
#                enabled: false
#                url:
#                username:
#                password:
#            # 初始连接数
#            initialSize: 5
#            # 最小连接池数量
#            minIdle: 10
#            # 最大连接池数量
#            maxActive: 20
#            # 配置获取连接等待超时的时间
#            maxWait: 60000
#            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#            timeBetweenEvictionRunsMillis: 60000
#            # 配置一个连接在池中最小生存的时间，单位是毫秒
#            minEvictableIdleTimeMillis: 300000
#            # 配置一个连接在池中最大生存的时间，单位是毫秒
#            maxEvictableIdleTimeMillis: 900000
#            # 配置检测连接是否有效
#            validationQuery: SELECT 1 FROM DUAL
#            testWhileIdle: true
#            testOnBorrow: false
#            testOnReturn: false
#            webStatFilter:
#                enabled: true
#            statViewServlet:
#                enabled: true
#                # 设置白名单，不填则允许所有访问
#                allow:
#                url-pattern: /druid/*
#                # 控制台管理用户名和密码
#                login-username:
#                login-password:
#            filter:
#                stat:
#                    enabled: true
#                    # 慢SQL记录
#                    log-slow-sql: true
#                    slow-sql-millis: 1000
#                    merge-sql: true
#                wall:
#                    config:
#                        multi-statement-allow: true

spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/ry?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
        slave_1:
          url: jdbc:mysql://localhost:3306/ry?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
      druid:
        # 初始连接数
        initialSize: 5
        # 最小连接池数量
        minIdle: 10
        # 最大连接池数量
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 配置一个连接在池中最大生存的时间，单位是毫秒
        maxEvictableIdleTimeMillis: 900000
        # 配置检测连接是否有效
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        stat:
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          multi-statement-allow: true